#!/usr/bin/env python3
"""Generate Cluster B — Professional client protocol intelligence."""
from __future__ import annotations
from pathlib import Path
import csv
from copy import deepcopy

ROOT = Path("/workspace/pranaforge-protocol-research/client-protocol-intelligence")

QUESTIONS = [
    (1, "Sleep onset after late / ruminative work"),
    (2, "Early waking or fragmented sleep"),
    (3, "Chronic stress / burnout risk"),
    (4, "Acute pre-performance anxiety"),
    (5, "Sustained focus / deep work"),
    (6, "Decision fatigue"),
    (7, "Emotional recovery after hard interpersonal load"),
    (8, "Occupational physical tension / MSD"),
    (9, "Travel / jet lag / schedule disruption"),
    (10, "Recovery after long high-demand day"),
    (11, "Low motivation / activation when depleted"),
    (12, "Rumination / worry loops"),
    (13, "Confidence / evaluation anxiety"),
    (14, "Rejection / failure / setback recovery"),
    (15, "Boundary / psychological detachment from work"),
    (16, "Afternoon energy crash"),
    (17, "Pre-meeting / presentation / pitch nerves"),
    (18, "Post-event cognitive residue"),
    (19, "Habit consistency under irregular schedules"),
    (20, "Relationship / social recovery capacity"),
]

DISCLAIMER = (
    "> **Disclaimer:** Educational personalization intelligence for PranaForge research — "
    "**not medical advice**, not psychotherapy, not a treatment plan. Not proprietary Daily Forge IP. "
    "CBT-I sleep restriction / stimulus control = **clinician-guided**. Individual skills do not replace "
    "organizational workload/culture fixes. Crisis → emergency/local professional help."
)

def proto(**kw):
    need = ["name","purpose","problem","typical","minimum","steps","when","short","longer",
            "mechanism","evidence","research","risks","avoid","sources","creator","tags","qnums"]
    for r in need:
        if r not in kw:
            raise ValueError(f"missing {r}")
    return kw

def P(base, **ov):
    d = deepcopy(base); d.update(ov); return proto(**d)

# Shared bases (abbreviated steps for compactness; full records still complete)
CYCLIC = dict(name="Cyclic Sighing (Physiological Sigh Pattern)", purpose="Rapidly reduce acute arousal via double-inhale + long exhale.", problem="Acute stress spike, elevated respiratory rate, pre-meeting nerves.", typical="5 min daily; 1–3 cycles acutely", minimum="1–3 sighs (~30–60 s)", steps=["Sit/stand upright.","Inhale slowly through nose until mostly full.","Second shorter nasal inhale to fully inflate.","Exhale slowly/fully through mouth or nose.","Repeat 1–3 cycles acutely or ~5 min as daily dose."], when="Acute spikes, pre-call, end-of-day downshift.", short="Often calmer affect and slower breathing within minutes.", longer="28-day RCT: daily cyclic sighing improved mood vs matched mindfulness; reduced resting respiratory rate (Balban 2023).", mechanism="Physiological sigh recruits alveoli; prolonged exhale increases parasympathetic influence.", evidence="B", research="Yilmaz Balban et al., Cell Rep Med 2023; PubMed 36630953.", risks="Lightheadedness if overdone; mouth dryness.", avoid="Severe respiratory disease, recent thoracic surgery, panic with breath-focus — use gentler long exhales.", sources="https://pubmed.ncbi.nlm.nih.gov/36630953/", creator="Studied by Balban/Huberman/Spiegel et al. (Stanford).", tags="Generic|High-value", qnums="4,17,18")

COHERENT = dict(name="Coherent / Resonance Frequency Breathing (~6 breaths/min)", purpose="Train HRV/RSA near ~0.1 Hz for autonomic downshift.", problem="Chronic stress load, low HRV, need trainable daily practice.", typical="10–20 min; ~5.5–6 breaths/min", minimum="5 min comfortable slow breathing", steps=["Sit upright; nasal breathe if comfortable.","Pace ~6/min (e.g., 5 s in / 5 s out) or personal resonance if biofeedback available.","Gentle depth — avoid overbreathing.","Optional pacer/HRV biofeedback."], when="Daily stress regulation; pre-sleep if not alerting.", short="Increased HRV/RSA during practice; often calmer mood.", longer="HRVB/resonance breathing: small–moderate benefits for stress/anxiety/BP in reviews.", mechanism="Respiration–HR–baroreflex resonance maximizes RSA (Lehrer/Vaschillo).", evidence="B", research="Lehrer & Gevirtz Front Psychol 2014; Steffen et al. 2017.", risks="Overbreathing dizziness; rare anxiety with interoception.", avoid="Severe lung disease; acute panic if breath focus worsens — shorten or guide clinically.", sources="https://pmc.ncbi.nlm.nih.gov/articles/PMC4104929/", creator="Paul Lehrer, Evgeny Vaschillo et al.", tags="Generic|High-value", qnums="3,10")

BOX = dict(name="Box Breathing (Square Breathing)", purpose="Stabilize attention/arousal with equal inhale–hold–exhale–hold.", problem="Performance anxiety, scattered attention under pressure.", typical="2–5 min (e.g., 4-4-4-4)", minimum="~1–2 min", steps=["Choose sustainable count (often 4 s).","Inhale nose → hold gently full → exhale → hold near-empty, equal counts.","Stop if dizzy; shorten/remove holds as needed."], when="Pre-performance, between tasks, tactical reset.", short="Subjective calm and attentional anchoring.", longer="Balban 2023: improved mood/anxiety similarly to other arms; not superior to cyclic sighing on primary outcomes.", mechanism="Paced breathing + mild holds provide structure; equal counts are heuristic not optimized resonance.", evidence="C", research="Comparator in Balban 2023; limited isolating RCTs for exact box pattern.", risks="Hold discomfort; dizziness.", avoid="Pregnancy, uncontrolled HTN, panic with holds, severe asthma — remove holds.", sources="https://pubmed.ncbi.nlm.nih.gov/36630953/", creator="Popularized in tactical/performance settings; single inventor unclear.", tags="Generic|Situation-specific", qnums="4,17")

PMR = dict(name="Progressive Muscle Relaxation (PMR)", purpose="Reduce somatic tension via systematic tense–release.", problem="Muscle guarding, occupational tension, arousal that blocks sleep onset.", typical="10–20 min full; 3–5 min brief (hands-shoulders-face)", minimum="3 min brief PMR", steps=["Tense one muscle group ~5 s without pain, then release 10–15 s.","Progress feet→face (or reverse); notice contrast.","Brief version: fists, shoulders, jaw/face only."], when="Wind-down; tension after desk/standing work; pre-sleep if body tense.", short="Reduced perceived muscle tension and anxiety for many.", longer="Longstanding clinical evidence base for anxiety/insomnia adjunct (package-level).", mechanism="Reduced muscle afferent drive; attentional shift; conditioned relaxation response.", evidence="B", research="Jacobson lineage; modern RCTs support PMR for anxiety/sleep as adjunct.", risks="Pain if over-tensile; avoid injured sites.", avoid="Acute injury, uncontrolled HTN for strong isometrics — use release-only cues.", sources="Clinical PMR literature; see parent master library.", creator="Edmund Jacobson (original); abbreviated clinical adaptations widely used.", tags="Generic|High-value", qnums="8,1")

STIM = dict(name="Stimulus Control Therapy (CBT-I Component) — Clinician-Guided Framing", purpose="Rebuild bed–sleep association; reduce conditioned arousal in bed.", problem="Insomnia with bed associated with wakeful worry/work.", typical="Ongoing nightly rules; clinician package often 4–8 weeks", minimum="Consistent application of core rules for several nights (under guidance)", steps=["Use bed only for sleep/sex (no work laptop in bed).","If unable to sleep after ~15–20 min quiet wakefulness, leave bed; return when sleepy.","Fixed wake time; avoid compensatory long lie-ins.","No clock-watching; dim light out of bed.","**Do not self-prescribe aggressive sleep restriction** — pair with clinician if restricting time-in-bed."], when="Chronic sleep-onset/maintenance insomnia with conditioned arousal.", short="May reduce time awake in bed within days–weeks when followed.", longer="Core A-tier CBT-I component in guidelines.", mechanism="Classical conditioning: extinguish bed–wake association; consolidate sleep drive.", evidence="A", research="CBT-I guideline literature; Bootzin stimulus control classic; AASM CBT-I recommendations.", risks="Temporary sleepiness; frustration; unsafe if sleep-deprived driving.", avoid="Bipolar spectrum / seizure risk without clinician; shift workers need adapted plans; never DIY aggressive restriction.", sources="AASM CBT-I guidance summaries; PubMed CBT-I reviews.", creator="Richard Bootzin (stimulus control); CBT-I packages (Morin, Espie lineages).", tags="Generic|High-value", qnums="1,2")

SRT = dict(name="Sleep Restriction Therapy (CBT-I Component) — Clinician-Guided ONLY", purpose="Consolidate fragmented sleep by temporarily limiting time-in-bed under clinical supervision.", problem="Severe sleep fragmentation / low sleep efficiency insomnia.", typical="Multi-week clinician-titrated schedule", minimum="N/A for DIY — requires clinician", steps=["Clinician sets initial time-in-bed from sleep diary sleep efficiency.","Fixed wake time; bedtime delayed to match prescribed window.","Titrate weekly as efficiency improves.","**Product rule:** never auto-prescribe restriction algorithms without clinician pathway."], when="Clinically significant insomnia with fragmentation — after assessment.", short="Often increased sleep pressure; temporary daytime sleepiness.", longer="Strong evidence within CBT-I packages for chronic insomnia.", mechanism="Homeostatic sleep drive consolidation; reduced wakefulness in bed.", evidence="A", research="CBT-I RCTs/meta-analyses; sleep restriction as key behavioral component.", risks="Daytime impairment, mood instability, mania risk in bipolar, seizure risk, accidents.", avoid="Anyone without clinician oversight; bipolar, epilepsy, safety-critical jobs until cleared.", sources="AASM/European insomnia guidelines; clinical CBT-I manuals.", creator="Spielman et al. (sleep restriction therapy).", tags="Generic", qnums="2")

II = dict(name="Implementation Intentions (If–Then Plans)", purpose="Automate desired response to a specific cue under stress/irregular schedules.", problem="Habit failure when willpower is depleted; missed recovery rituals.", typical="2–5 min to write; lifelong reuse", minimum="One precise if–then", steps=["Identify critical cue (e.g., 'When I close the laptop after 9pm…').","Specify exact action ('…I plug phone outside bedroom and start 5 cyclic sighs').","Rehearse once mentally; keep plan visible for 1 week."], when="Irregular schedules; travel; protecting sleep/boundaries.", short="Higher follow-through vs vague goals in many studies.", longer="Large evidence base for goal attainment (Gollwitzer).", mechanism="Cue–response links reduce deliberation under fatigue.", evidence="A", research="Gollwitzer meta-analyses on implementation intentions.", risks="Overly rigid plans that ignore safety; plan proliferation.", avoid="None major; keep plans few and specific.", sources="Gollwitzer implementation intention literature.", creator="Peter Gollwitzer.", tags="Generic|High-value|Lifestyle-specific", qnums="19,15")

WOOP = dict(name="WOOP (Mental Contrasting + Implementation Intentions)", purpose="Combine desired future with obstacle realism + if–then plan.", problem="Wishful goals that collapse under real obstacles (travel, deadlines).", typical="5–10 min", minimum="~5 min one cycle", steps=["Wish: name important feasible wish.","Outcome: best result if achieved.","Obstacle: main inner obstacle.","Plan: if [obstacle], then [action]."], when="Weekly planning; behavior change under high demand.", short="More realistic commitment; reduced pure fantasy.", longer="RCTs support mental contrasting + II for behavior change.", mechanism="Mental contrasting energizes goal pursuit when expectancy is sufficient; II automates obstacle response.", evidence="A", research="Oettingen mental contrasting / WOOP research program.", risks="Demotivation if wish is unrealistic — reframe wish.", avoid="None major.", sources="woopmylife.org educational materials; Oettingen publications.", creator="Gabriele Oettingen (mental contrasting); WOOP branding for public use.", tags="Generic|High-value", qnums="3,14,19")

AL = dict(name="Affect Labeling (Putting Feelings into Words)", purpose="Reduce amygdala reactivity by briefly naming emotion.", problem="Emotional flooding after hard calls/cases; unnamed arousal.", typical="30–90 s", minimum="One precise label aloud or written", steps=["Pause; notice body activation.","Name feeling specifically ('frustrated + anxious', not just 'bad').","Optional: one sentence cause without story spiral.","Return to next task or recovery protocol."], when="Post-conflict, post-bad-news, emotional residue.", short="Often slight downshift in intensity.", longer="fMRI/behavioral work supports labeling reducing emotional reactivity (Lieberman lineage).", mechanism="Prefrontal linguistic processing dampens limbic response.", evidence="B", research="Lieberman et al. affect labeling neuroimaging; related emotion-regulation literature.", risks="Rumination if labeling becomes lengthy analysis — keep brief.", avoid="Active trauma processing needs clinician — not DIY exposure.", sources="Affect labeling literature (Lieberman).", creator="Research program associated with Matthew Lieberman et al.", tags="Generic|Situation-specific|High-value", qnums="7,18")

SW = dict(name="Scheduled Worry / Postpone Worry", purpose="Contain rumination to a bounded slot to free focus and sleep onset.", problem="Work worry invading evenings/bed.", typical="10–15 min scheduled slot", minimum="5 min capture + postpone", steps=["When worry arises outside slot: jot 1 line, say 'I'll worry at 6:30pm'.","At slot: list worries 10–15 min; pick one actionable next step or park it.","Close notebook; do wind-down (light hygiene / breath)."], when="Evening rumination; sleep-onset worry.", short="Reduced intrusive worry for many when practiced consistently.", longer="Used in CBT for GAD/insomnia adjunct packages.", mechanism="Stimulus control for worry; reduces continuous monitoring.", evidence="B", research="Borkovec-style stimulus control for worry; CBT packages.", risks="Avoidance of needed action — always extract one actionable item when appropriate.", avoid="Acute crisis safety issues — do not postpone risk assessment.", sources="CBT worry-control literature.", creator="Popularized in CBT (Borkovec and successors).", tags="Generic|High-value|Situation-specific", qnums="12,1")

BA = dict(name="Tiny Behavioral Activation Step", purpose="Counter depletion/anhedonia with smallest valued action.", problem="Low motivation when burned out or post-setback.", typical="2–10 min action", minimum="2-minute start", steps=["Pick valued domain (body, social, mastery).","Shrink to ridiculous-small step (shoes on; send one text; open doc and write one sentence).","Do it without mood as prerequisite; notice completion."], when="Depleted mornings; post-rejection; depressive slide (non-crisis).", short="Slight activation; breaks inertia.", longer="Behavioral activation is A-tier for depression in clinical packages — here used as micro self-management, not therapy substitute.", mechanism="Action→reward loop; reduces avoidance.", evidence="A", research="Behavioral activation RCTs for depression (clinical); micro-BA adapted for self-management.", risks="Pushing through medical illness; masking need for care.", avoid="Severe depression/suicidality — seek care; don't use BA as sole treatment.", sources="Dimidjian/Martell BA literature (clinical context).", creator="Lewinsohn lineage; modern BA (Martell, Dimidjian et al.).", tags="Generic|High-value", qnums="11,14")

POMO = dict(name="Focused Work Block + Break (Pomodoro-style)", purpose="Protect deep work with timed focus + mandatory micro-recovery.", problem="Context switching, endless screens, attention fragmentation.", typical="25/5 or 50/10 min", minimum="One 25-min protected block", steps=["Define single outcome for the block.","Silence notifications; start timer.","On break: stand, look far, 3 cyclic sighs — no new inputs.","After 3–4 blocks, longer break."], when="Deep work days; coding; writing; analysis.", short="Better completion rate; less continuous strain.", longer="Timeboxing evidence mixed/package-level; useful as attention hygiene heuristic (C).", mechanism="Limits continuous cognitive load; reinforces detachment micro-breaks.", evidence="C", research="Cirillo Pomodoro method (popular); related attention-rest literature.", risks="Rigidity; interrupting flow states — adapt lengths.", avoid="None major.", sources="Cirillo Pomodoro method; attention restoration adjacent work.", creator="Francesco Cirillo (Pomodoro Technique branding).", tags="Generic|Situation-specific", qnums="5,6,16")

LIGHT = dict(name="Morning Outdoor Light Timing", purpose="Anchor circadian phase with morning outdoor light.", problem="Social jet lag, travel, shift-ish schedules, low morning alertness.", typical="10–30 min outdoor light within ~1 h of wake", minimum="~5–10 min bright outdoor light (longer if overcast)", steps=["Within ~60 min of wake, go outdoors without sunglasses if safe.","Face general outdoor brightness (not stare at sun).","Keep wake time relatively fixed."], when="Most days; especially after late nights or travel.", short="Often improved alertness; circadian cueing.", longer="Strong circadian science; light timing is A-tier for phase alignment.", mechanism="ipRGC→SCN photic resetting.", evidence="A", research="Chronobiology light literature; Czeisler/Wright et al. circadian work.", risks="UV exposure — use shade/hat as needed; never stare at sun.", avoid="Photosensitivity conditions — modify with clinician/ophthalmology advice.", sources="Circadian light-timing reviews.", creator="Foundational chronobiology (many labs); public protocols widely popularized.", tags="Generic|Lifestyle-specific|High-value", qnums="9,16,2")

CAFF = dict(name="Caffeine Timing Cutoff", purpose="Protect sleep by stopping caffeine with adequate half-life buffer.", problem="Late caffeine delaying sleep onset in knowledge workers.", typical="Cutoff ~8–10 h before target bedtime (individualize)", minimum="No caffeine after mid-afternoon for sensitive sleepers", steps=["Estimate bedtime; set cutoff ~8–10 h prior (or earlier if sensitive).","Switch to non-caffeinated rituals after cutoff.","Track sleep onset for 1 week; adjust."], when="Chronic delayed sleep onset; high coffee culture professions.", short="May improve sleep latency within days.", longer="Pharmacokinetic rationale strong; sleep hygiene component with good face validity (B).", mechanism="Adenosine receptor antagonism delaying sleep pressure signaling.", evidence="B", research="Caffeine + sleep literature; Drake et al. caffeine timing studies.", risks="Withdrawal headache if abrupt — taper.", avoid="None major; medical caffeine uses need clinician input.", sources="Sleep caffeine timing studies.", creator="N/A (pharmacology + sleep hygiene practice).", tags="Generic|Lifestyle-specific|High-value", qnums="1,9")

WIND = dict(name="Behavioral Wind-Down Routine", purpose="Create predictable pre-sleep sequence to reduce arousal.", problem="Hard stop from high-stimulation work to bed.", typical="30–60 min", minimum="15 min dim + offline sequence", steps=["Dim lights; warm color temperature.","Park work (notebook capture) — no new email.","Optional: PMR or coherent breathing 5–10 min.","Same sequence nightly when possible."], when="Most nights; critical after late client work.", short="Easier sleep onset for many.", longer="Sleep hygiene package component (C as standalone; stronger inside CBT-I).", mechanism="Stimulus control + reduced cognitive/physiological arousal.", evidence="C", research="Sleep hygiene reviews; CBT-I packages include wind-down elements.", risks="Perfectionism about routine — keep flexible when travel.", avoid="None major.", sources="CBT-I / sleep hygiene educational materials.", creator="Sleep medicine practice packages.", tags="Generic|Lifestyle-specific", qnums="1,10")

DET = dict(name="Psychological Detachment Boundary Ritual (Recovery Experience)", purpose="Mentally separate from work to enable recovery (Sonnentag).", problem="Always-on roles; blurred boundaries; poor evening recovery.", typical="5–15 min end-of-day ritual", minimum="3 min shutdown + device park", steps=["Write tomorrow's top 3; close loops on paper.","Explicit shutdown phrase ('Work is parked until X').","Park devices out of bedroom; change clothes/context.","Do one non-work mastery or relaxation activity."], when="End of day; after last client message; travel hotel arrival.", short="Reduced cognitive residue; better evening affect for many.", longer="Psychological detachment robustly linked to well-being in occupational recovery research (Sonnentag & Fritz).", mechanism="Recovery experience model: detachment, relaxation, mastery, control.", evidence="B", research="Sonnentag & Fritz 2007 recovery experiences; subsequent occupational health work.", risks="Guilt about detaching in always-on cultures — pair with team norms.", avoid="On-call safety roles need adapted 'partial detachment' plans.", sources="Sonnentag recovery literature; attorney recovery PMC11182056 citing framework.", creator="Sabine Sonnentag, Charlotte Fritz (recovery experiences framework).", tags="Generic|Profession-specific|High-value", qnums="15,18,20")

VAL = dict(name="Values Compass (Brief ACT/Values Clarification)", purpose="Reconnect action to chosen values under burnout cynicism.", problem="Depersonalization, meaning loss, values drift.", typical="5–10 min", minimum="3 min pick one valued action", steps=["Name 1–2 valued domains (craft, care, family, integrity).","Rate recent alignment 0–10.","Choose one tiny valued action today."], when="Burnout cynicism; ethical stress; weekly review.", short="Slight increase in purposefulness.", longer="ACT values work supported in packages; brief self-help is C.", mechanism="Values-consistent action reduces experiential avoidance.", evidence="C", research="ACT clinical literature (Hayes); brief values tools as derivatives.", risks="Should not replace therapy for clinical depression.", avoid="Acute crisis — seek care.", sources="ACT educational materials.", creator="Steven C. Hayes et al. (ACT); brief tools adapted widely.", tags="Generic|Profession-specific", qnums="3,20")

REAPP = dict(name="Cognitive Reappraisal", purpose="Change emotional impact by reframing meaning of a situation.", problem="Catastrophic interpretations of setbacks, evaluations, rejections.", typical="2–5 min", minimum="One alternative appraisal written", steps=["Name situation + automatic thought.","Generate 1–2 alternative appraisals that are realistic (not toxic positivity).","Choose action consistent with valued goal."], when="Post-rejection; negative feedback; evaluation anxiety.", short="Reduced intensity of negative emotion often.", longer="Gross process model; strong basic evidence (A for skill in lab/clinical packages).", mechanism="Prefrontal reinterpretation alters emotional trajectory.", evidence="A", research="James Gross emotion regulation process model; reappraisal meta-analyses.", risks="Forced positivity; invalidating real injustice — use realistic reframes.", avoid="Trauma processing without clinician.", sources="Gross emotion regulation literature.", creator="James J. Gross (process model popularization).", tags="Generic|High-value|Situation-specific", qnums="13,14")

SD = dict(name="Self-Distancing Reflection", purpose="Reflect on stressors from slightly distanced perspective to reduce immersion.", problem="Immersive rumination after conflicts/cases.", typical="3–8 min", minimum="2 min", steps=["Recall event briefly.","Rewrite using own name / 'you' (distanced language) OR imagine fly-on-wall view.","Ask: what advice to a colleague? Extract one lesson + one next step."], when="Post-mortem after conflict; evening residue.", short="Less emotional immersion; clearer takeaways.", longer="Kross/Ayduk self-distancing research program (B).", mechanism="Linguistic/psychological distance reduces emotional reactivity while preserving insight.", evidence="B", research="Kross & Ayduk self-distancing studies.", risks="Avoidance if used to never feel — balance with labeling.", avoid="Active trauma — clinical care.", sources="Self-distancing literature (Kross).", creator="Ethan Kross, Ozlem Ayduk et al.", tags="Generic|Situation-specific", qnums="12,18")

ART = dict(name="Brief Attention Restoration (Soft Fascination Break)", purpose="Restore directed attention via soft-fascination environments.", problem="Directed attention fatigue after deep cognitive work.", typical="5–20 min", minimum="5 min window/nature micro-break", steps=["Leave screen; look at sky/trees/distant view or quiet indoor plants.","No phone scroll.","Optional short walk without podcast."], when="Between deep blocks; afternoon crash.", short="Subjective mental refresh for many.", longer="Attention Restoration Theory (Kaplan); evidence mixed/moderate for nature micro-breaks (C).", mechanism="Soft fascination allows directed-attention networks to recover.", evidence="C", research="Kaplan ART; nature-break studies heterogeneous.", risks="None major.", avoid="None major.", sources="Kaplan Attention Restoration Theory literature.", creator="Rachel & Stephen Kaplan (ART).", tags="Generic", qnums="16,5")

print("bases loaded")
